FROM node:20.15.0-bullseye

RUN npm install -g npm@latest --force && npm install --global yarn --force

WORKDIR /app

COPY . /app

RUN yarn

EXPOSE 31299

VOLUME [ "/app" ]

CMD [ "yarn", "mock-config-server" ]
